# Define a Kubernetes Secret for application secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
data:
  MYSQL_PASSWORD: bmV3cGFzc3dvcmQxMjM=
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkNDU2=
